name: Context Variable Workflow
on:
  workflow_dispatch: # for manual trigger of an workflow
env:
  cloud: GCP

jobs:
  GCP-Deployment :
    runs-on: ubuntu-latest
    steps:
      - name: Test context variable
        run: |
          echo "Repository name :-  ${{github.repository}}"
          echo "Repository name :-  ${{github.workflow}}"
     
